### ISSUE TITLE
Cannot push

### ISSUE THREAD

**Issue by mlep** [JabRef/blog.jabref.org#3]
To create a blog post, I am trying to push a picture. However, I get: 
> remote: Permission to JabRef/blog.jabref.org.git denied to mlep.
> fatal: unable to access 'https://github.com/JabRef/blog.jabref.org.git/': 
> The requested URL returned error: 403

Any alternative?

**Comment by koppor** [comment]
Fixed. You the only non-developer having write access.

**Comment by mlep** [comment]
Thanks!
