### ISSUE TITLE
Blog entries should have colors alternating

### ISSUE THREAD

**Issue by koppor** [JabRef/blog.jabref.org#36]
Currently, two consecutive blog entries have to be configured within them to have colors alternating. This should be done by the template.

bg and color should be set by the template

Examples: https://github.com/JabRef/blog.jabref.org/blob/gh-pages/_posts/2019-08-27-JabCon-Release.md and https://github.com/JabRef/blog.jabref.org/blob/gh-pages/_posts/2019-10-03-Hacktoberfest.md

**Comment by sumitkharche** [comment]
@koppor I can work on it. The coloring sequence is disturbed from this " 2017-04-17-JabRef4-0-beta.md " post.

**Comment by koppor** [comment]
The Jekyll template has to be fixed so that `bg` and `color` is not needed on **any** post anymore!

**Comment by koppor** [comment]
Starting point: https://github.com/JabRef/blog.jabref.org/blob/gh-pages/_layouts/default.html

**Comment by koppor** [comment]
Not relevant any more
