### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by CsatiZoltan** [JabRef/blog.jabref.org#41]
Please provide an RSS feed link so that I am notified when a new blog entry shows up.

**Comment by Siedlerchr** [comment]
Thanks for your idea, this is already possible:
http://blog.jabref.org/feed.xml
(In the top left corner we have the "RSS" symbol)

**Comment by CsatiZoltan** [comment]
Thanks. That icon was not displayed in Firefox (probably one of my extensions banned it), but now I see it in another browser.
