### ISSUE TITLE
New blog entry

### ISSUE THREAD

**Issue by teertinker** [JabRef/blog.jabref.org#48]
Hello,
I tried to create a blog post, that deals with the LibreOffice integration. My suggestion can be found at: https://github.com/teertinker/blog.jabref.org/pulls . However, I don't know how to submit my suggestion to the JabRef Blog. May be someone can help or do the merging.

**Comment by Siedlerchr** [comment]
Hi, you need to create the PR in this repository and then select your  branch from your repo

**Comment by teertinker** [comment]
Thank you.

**Comment by koppor** [comment]
Submitted at https://github.com/JabRef/blog.jabref.org/pull/49.
