### ISSUE TITLE
Logo contest

### ISSUE THREAD

**Issue by mlep** [JabRef/blog.jabref.org#5]
I have just discovered JabRef has a Facebook page, and that there is a logo contest.
This contest should be announced on the Blog (and on Discourse) too.

**Comment by mlep** [comment]
- For the blog, see https://github.com/JabRef/blog.jabref.org/pull/6
- For Discourse, see http://discourse.jabref.org/t/a-new-icon-for-jabref-contest-and/158
  - Note: the category should be changed from **Help** to **News** (I could not select *News*)

**Comment by mlep** [comment]
Since the contest is about to end...
(I wish I had learn about the contest earlier)

**Comment by koppor** [comment]
@matthiasgeiger Could you check why @mlep cannot create "News" in Discourse?

**Comment by matthiasgeiger** [comment]
Because he is no moderator/admin and: 

> "You've reached the maximum of 5 staff users for your current hosting plan."
