### ISSUE TITLE
Recently updated section is outdated

### ISSUE THREAD

**Issue by tobiasdiez** [JabRef/blog.jabref.org#71]
Showing 
```
[JabRef 5.0 Major Release](https://blog.jabref.org/2020/03/09/JabRef5-0/)
    [GSOC22 — Implement a Three Way Merge UI for merging BibTeX entries](https://blog.jabref.org/2022/08/13/GSOC22-Three-Way-Merge/)
    [Customize entry types in JabRef: Video tutorial](https://blog.jabref.org/2016/09/19/CustomEntryTypesVideoTut/)
    [JabRef 4.0](https://blog.jabref.org/2017/10/04/JabRef4-0/)
    [JabCon 2022](https://blog.jabref.org/2022/09/05/JabCon22/)
```
instead of the latest releases.
Not sure if this section is needed at all.

**Comment by koppor** [comment]
It shows updated posts not being recently posted: https://github.com/cotes2020/jekyll-theme-chirpy/issues/800#issuecomment-1353153943. 

Raised a support question at https://talk.jekyllrb.com/t/chirpy-how-to-disable-recently-updated/8135

**Comment by Siedlerchr** [comment]
There no longer is a recently updated secion on the website, closing this issue and it seems to have been solved https://github.com/cotes2020/jekyll-theme-chirpy/pull/1456
